# Generated by Django 3.0.4 on 2020-03-10 00:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='1', max_length=128, unique=True, verbose_name='name')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_created')),
                ('description', models.CharField(default='', max_length=128, verbose_name='description')),
                ('is_delete', models.BooleanField(default=False, verbose_name='is_delete')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.BooleanField(default=True, verbose_name='owner')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_created')),
                ('word', models.CharField(default='什么都没写吗？', max_length=256, verbose_name='word')),
                ('is_delete', models.BooleanField(default=False, verbose_name='is_delete')),
            ],
        ),
    ]
