# Generated by Django 3.0.4 on 2020-03-18 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepageapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date_created'),
        ),
    ]
