# Generated by Django 3.0.4 on 2020-05-24 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepageapp', '0002_auto_20200318_0650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='description',
        ),
        migrations.AddField(
            model_name='photo',
            name='img',
            field=models.ImageField(null=True, upload_to='photos'),
        ),
    ]
