# Generated by Django 3.0.4 on 2020-05-26 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepageapp', '0003_auto_20200524_2254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='img',
            new_name='src',
        ),
    ]
