# Generated by Django 3.0.4 on 2020-05-26 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepageapp', '0004_auto_20200526_0427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='name',
            new_name='info',
        ),
    ]
