# Generated by Django 3.0.4 on 2020-06-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepageapp', '0005_auto_20200526_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='info',
            field=models.CharField(default='1', max_length=128, unique=True, verbose_name='info'),
        ),
        migrations.AlterField(
            model_name='word',
            name='owner',
            field=models.CharField(choices=[('wsy', '魏疏影'), ('zff', '张非凡')], default='wsy', max_length=128),
        ),
    ]
